### PR TITLE
Support build 37 and 38 rebased

### PR DESCRIPTION
**Pull request by jcfr**
@dbrnz @dand-oss This PR includes you respective set of changes :pray:  and is based on current master. 

I will post here comment and questions.

Ultimately, some more commit may be squashed. Also to give credit, relevant `Co-authored-by: ...` git message trailer will be added.

### CODE REVIEW

**Comment by jcfr** [comment]
@dbrnz when integrating the change of @dand-oss in #256, you reverted `python uses external libffi now`, was this intentional ?

**Comment by dbrnz** [comment]
@jcfr reverting `libffi` changes wasn't intentional, so please unrevert as applicable...

**Comment by dbrnz** [comment]
Hmm @jcfr , commit c59e3d1 of @dand-oss (rebased as commit 77d11f7 and which I did merge), resulted in:
```
# get libffi
find_path(FFI_INCLUDE_DIR ffi.h)
find_library(FFI_LIBRARY NAMES ffi libffi)
add_python_extension(_ctypes
    SOURCES ${ctypes_COMMON_SOURCES}
    INCLUDEDIRS ${FFI_INCLUDE_DIR}
    LIBRARIES ${FFI_LIBRARY}
)
```
when not `APPLE`. This code is now missing as a result of commit 3554d50. Shouldn't the above apply for Python 3.7, so we end up with:
```
if(PY_VERSION VERSION_LESS "3.7")
    set(_libffi_sources)
    set(_libffi_include_dirs)
      .
      .
      .
    add_python_extension(_ctypes
        SOURCES ${ctypes_COMMON_SOURCES} ${_libffi_sources}
        ${_libffi_include_dirs}
    )
else()
    find_path(FFI_INCLUDE_DIR ffi.h)
    find_library(FFI_LIBRARY NAMES ffi libffi)
    add_python_extension(_ctypes
       SOURCES ${ctypes_COMMON_SOURCES}
       INCLUDEDIRS ${FFI_INCLUDE_DIR}
       LIBRARIES ${FFI_LIBRARY}
    )
endif()
```

**Comment by jcfr** [comment]
Good catch. That would indeed make more sense.

**Comment by dand-oss** [comment]
Wow, you guys have done a lot!

Anything you need me to add here?

**Comment by jcfr** [comment]
> reverting libffi changes wasn't intentional, so please unrevert as applicable...

@dbrnz  Thanks for the review, this last commit should do it.

**Comment by jcfr** [comment]
> Wow, you guys have done a lot!

Thanks :smile: 

> Anything you need me to add here?

@dand-oss doing some local testing of the branch would be helpful.

>

**Comment by dand-oss** [comment]
> @dand-oss doing some local testing of the branch would be helpful.

Here is how I "checked out a local branch"
for those contributors who like me are less than git wizards
its not difficult!

``
# I had a forked repo of python-cmake-buildsystem cloned to my local
# with a remote and a branch named "upstream" which I regular rebase my "master" branch upon

# get the remote branch as a local branch
remote add jcfr git@github.com:jcfr/python-cmake-buildsystem.git
git fetch jcfr
git checkout -b support-build-37-and-38-rebased jcfr/support-build-37-and-38-rebased

# get support-build-37-and-38-rebased
git rebase -i upstream

# get my master branch on top of the trial branch
# - custom cmake, ability to build debug, my own scripts to set up venv after build
git checkout master
git rebase -i support-build-37-and-38-rebased
``

Then I built on windows and Linux, and all was good!

**Comment by jcfr** [comment]
> Then I built on windows and Linux, and all was good!

Great. Thanks for taking the time to test :pray:

**Comment by jamesobutler** [comment]
Based on the title of this PR “ Support build 37 and 38 rebased“, is this PR waiting on [Python 3.8.0](https://www.python.org/downloads/release/python-380/) support to be added? It doesn’t currently appear to be in this PR.

**Comment by dand-oss** [comment]
Python 3.8 will not build - requires more work

CMake Error at cmake/libpython/CMakeLists.txt:450 (add_executable):
  Cannot find source file:

    build-64/Python-3.8.0/Parser/bitset.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at cmake/libpython/CMakeLists.txt:477 (add_library):
  Cannot find source file:

   build-64/Python-3.8.0/Modules/zipimport.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  cmake/libpython/CMakeLists.txt:513 (add_libpython)

CMake Error at cmake/libpython/CMakeLists.txt:450 (add_executable):
  No SOURCES given to target: pgen

CMake Error at cmake/libpython/CMakeLists.txt:477 (add_library):
  No SOURCES given to target: libpython-shared
Call Stack (most recent call first):
  cmake/libpython/CMakeLists.txt:513 (add_libpython)

CMake Error at cmake/libpython/CMakeLists.txt:406 (add_executable):
  No SOURCES given to target: _freeze_importlib

**Comment by jamesobutler** [comment]
## Testing Python 3.7 support
- I'm having trouble generating the solution for the default configuration in this PR for 3.7.4.  
```
CMake Error at cmake/libpython/CMakeLists.txt:493 (add_library):
  Cannot find source file:

    C:/D/Python-3.7.4/Modules/zlib/adler32.c
```
This appears to be because zlib (only used for Windows) was removed from the cpython repository to be in cpython-source-deps as specified in  https://github.com/python/cpython/commit/d01db1c2a2a71455163a1d3b214cc8dc27201303#diff-bf17ac149e2e7a530c677e9bd51d3fd2 starting with python 3.7.0.

## Testing Python 3.8 support
- Regarding failures mentioned by @dand-oss:
```log
CMake Error at cmake/libpython/CMakeLists.txt:450 (add_executable):
Cannot find source file:

build-64/Python-3.8.0/Parser/bitset.c
```
```log
CMake Error at cmake/libpython/CMakeLists.txt:450 (add_executable):
No SOURCES given to target: pgen
```
Bitset.c and pgen were removed in python 3.8.0 as part of https://github.com/python/cpython/commit/1f24a719e7be5e49b876a5dc7daf21d01ee69faa.

```log
CMake Error at cmake/libpython/CMakeLists.txt:477 (add_library):
Cannot find source file:

build-64/Python-3.8.0/Modules/zipimport.c
```
Zipimport was rewritten in pure python for 3.8.0.  It is now at Lib/zipimport.py.  See https://github.com/python/cpython/commit/79d1c2e6c9d1bc1cf41ec3041801ca1a2b9a995b

**Comment by dand-oss** [comment]
Status

I am using cmake-buildystem with Python 3.7.6 on Windows and Linux

python 3.8 will take significant work - much has changed...  

I put a few hours in on 3.8, worked around some problems, but more problems remain.

**Comment by gongminmin** [comment]
I have changes to adapt 3.7 and 3.8. It's not a general enough change, only works for my scenario. Feel free to pick useful lines from them.

3.7: https://github.com/gongminmin/python-cmake-buildsystem/commit/7d97c1d178a8015bf6397eecf742ba36aafceed3
3.8: https://github.com/gongminmin/python-cmake-buildsystem/commit/d4818e7002b5b72f9fe606738baea5e5b3612f16

**Comment by jcfr** [comment]
Closing. This pull-request is superseded by https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/289 and https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/292

**Pull request closed without merging**
