### PR TITLE
Remove arguments from else and end* block termination commands

### PR DESCRIPTION
**Pull request by adrianbroher**
I took the liberty to partially implement issue #7.  The attached patch removes all arguments from the else and end* block termination commands.  CMake doesn't complain about any syntax errors with the PR applied.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the PR. 

To avoid merge conflicts, I suggest we integrate your patch after PR #113 is integrated.

**Comment by adrianbroher** [comment]
> To avoid merge conflicts, I suggest we integrate your patch after PR #113 is integrated.

Sure thing. Just ping me when I should rebase this PR.

**Comment by jcfr** [comment]
Sounds good :+1: 

Thanks for the help.

**Comment by adrianbroher** [comment]
I've updated the patch accordingly.

However I noticed something that seems to be a bug in the py3k code. I will write a line comment there.

**Comment by adrianbroher** [comment]
Well, Github doesn't let me write my line comment.  I'm talking about [cmake/extensions/CMakeLists.txt:377][1]. Shouldn't this be an `elseif` instead of an `else`?

[1]: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/master/cmake/extensions/CMakeLists.txt#L377

**Comment by jcfr** [comment]
@adrianbroher Thanks for review :smile:   Good catch :+1: 

Submitting a patch now,

**Comment by jcfr** [comment]
Re: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/114#issuecomment-202830758

Fixed in https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/commit/ce81ce25db7ab97e3a8dbbe8bc46df265e14e694

**Pull request merged**
