### PR TITLE
Add WITH_STATIC_DEPENDENCIES and WITH_STATIC_EXECUTABLES options

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@chuckatkins Let me know what you think.

**Comment by chuckatkins** [comment]
The removal of anything using dlopen shouldn't be happening.  Even if libpython.a is built statically, you can still use dlopen functionality.  It just requires that whatever executable it's linked into, uses the shared C runtime, i.e. libc.so, instead of libc.a. That in turn means the try-compiles need to stay so the configure checks for dlopen function correctly.

**Comment by BestPig** [comment]
Your binary is statically compiled, but cannot be used in an clean environment.
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

There is another project that patch python to create a real independent static-python if you are interested https://code.google.com/p/pts-mini-gpl/source/browse/trunk/staticpython/build.sh

**Comment by chuckatkins** [comment]
"Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]"

This is a consequence of building with all built-in.  The heuristics in bin/python that look for exec_prefix expect there to be a lib/python2.6/dynload folder which doesn't exist if no shared objects get built.  See #73 for the fix

**Comment by chuckatkins** [comment]
There was actually a CMake bug that rally prevented this from working correctly, dealing with how -Wl,Bdynamic and -Wl,Bstatic are passed to the compiler and linker.  I've fixed upstream CMake master so this works now and am getting one more new policy into CMake to make sure all the link flags propagate to try_compile correctly (needed to support some HPC compilers).  I don't believe we can reliably support both cases of static-dep+dynamic-runtime and static-deps+static-runtime without these CMake patches.  On the bright side, it will make the implementation in here much cleaner because we can restrict the availability of these options to require a new CMake with these features.

**Comment by BestPig** [comment]
Thanks @chuckatkins, it works, but I was hopping the all build-in option was embedding all files required in lib/python2.6/.

**Comment by chuckatkins** [comment]
It embeds all the compiled code into libpython but all the .py files still need to be there.  To embed everything would be building a frozen python instead of static.

**Comment by chuckatkins** [comment]
Note, I've got another implementation of this but I'm waiting on a new CMake policy I'm implementing that will drop "-rdynamic" by default.  It doesn't matter for GCC but without it the build breaks with other compilers.

**Comment by jcfr** [comment]
@chuckatkins Thanks for the note, in the mean time I am keeping the PR open.

**Comment by jcfr** [comment]
3763bb3 will be integrated separately as part of #86

**Comment by jcfr** [comment]
Copied from https://github.com/chuckatkins/python-cmake-buildsystem/commit/da6350a3f394fc682601038d130cc2613deaa600#commitcomment-13143879 

```
I've been on a big push to get native static builds working in the ParaViewSuperbuild
with a slew of different compilers. I'm almost done and I'll get the static_deps branch
updated as soon as my commit to CMake makes it to cmake/master.
```

**Comment by jcfr** [comment]
@chuckatkins do you know what the status on this ?  

Ps: Support for Python 3.5.1 has just been integrated.

**Comment by chuckatkins** [comment]
You can close it.  The work on this has stalled and become unnecessary since I overhauled CMake's built in support for the Cray tool chain.

**Comment by jcfr** [comment]
Great.

For reference, are the commits related to CrayPrgEnv:

kitware/CMake@64e26850fc2a98994424a34eada9bec90f384c7e

    CrayPrgEnv: Cleanup binaries from implicit compile flag detection

kitware/CMake@928d2085d8ebeadc498e9e9f884b8adabf3346c3

    CrayPrgEnv: Don't use absolute paths for imlicit libraries
    
    When parsing implicit include dirs, link dirs, and link libs, all
    arguments are resolved to absolute paths instead of relative paths.
    This is correct for link and include directories but link libraries
    should only include the library name, not it's path.

kitware/CMake@a7ef02253bf8ef33d4ffdd761802ea30ef289b8a

    Cray: Refactor the Cray platform files to use compiler wrapper checks
    
    This is an extensive refactoring of the Cray compiler wrapper usage.
    Using the new compiler wrapper checks, the CrayPrgEnv info files have
    been moved from Platform/ to Compiler/.  The adjusted naming convention
    allows the compiler-wrapper information files to be loaded for both the
    CrayLinuxEnvironment platform when cross-compiling and the Linux
    platform if building natively on the Cray compute nodes.  It also
    creates a separation of common arguments for compiler id and language
    information used to perform the appropriate introspection of implicit
    arguments and libraries used by the compiler wrappers based on the
    loaded module environment.

kitware/CMake@0763a8365528166747746e3b94e74ca98d0d705f

    Cray: Add macro tests to detect the Cray compiler wrappers

kitware/CMake@5eaac0c96ac51e1300664ef37239f3215bb58489

    Compiler: Add infrastructure for detecting compiler wrappers

kitware/CMake@71e5f253f9b035be7049f36dab2e942220ff6209

    Fortran: Add ftn, the Cray compiler wrapper, to the default search.

kitware/CMake@743fcf1e89a5e5172d46a3202b123bc441ec42ba

    Cray: Fix static / dynamic detection logic and parse more driver flags

kitware/CMake@31d52139ca30f5c0fb814765da542d44531ca146

    Cray: Added documentation for cross compiling on a Cray

kitware/CMake@c54a621b55dd09f212037cacb35b98b5129afd40

    Cray: New platform file for Cray Linux Environment and PrgEnv

**Comment by jcfr** [comment]
And the one related to improvement of static support in CMake:

kitware/CMake@e90f463a312e18fd6498799de1522b96d84fd012

    Drop executable symbol export if platform does not support shared libs
    
    Instead of always adding CMAKE_SHARED_LIBRARY_LINK_<LANG>_FLAGS to
    executables, or just when the ENABLE_EXPORTS property is set (CMP0065),
    make sure that the target platform also actually supports shared
    libraries.  If not, then the executable cannot possibly provide symbols
    to them anyway.

kitware/CMake@b15f4e9b86bc3dc31b6a01c0ffc30747f467ec1f

    try_compile: Propogate CMP0065 to the generated project.
    
    Set policy CMP0065 to the value used in the calling project.
    
    Set the the value of CMAKE_ENABLE_EXPORTS if set in the calling
    project to initialize the target property appropriately.

kitware/CMake@9784af1b50a142c0160058734c7e12cee5f2a15e

    CMP0065: Restrict the use of CMAKE_SHARED_LIBRARY_LINK_<LANG>_FLAGS
    
    This new policy restricts the addition of the shared library link flags
    to executables only when the ENABLE_EXPORTS property is set to True.

kitware/CMake@7f0b83e0185f4e131110a61d898cec4a96bd9a7d

    try_compile: Update documentation for other propagated variables

kitware/CMake@fb77c2c54bc341e76a83f646e6d75662c44179fc

    try_compile: Propogate the CMAKE_LINK_SEARCH_ variables

kitware/CMake@675ef165f213a6db1f9d0dfbebf6a0afc5469494

    Allow LINK_SEARCH_{START,END}_STATIC props to have default values.
    
    Use the CMAKE_LINK_SEARCH_START_STATIC and CMAKE_LINK_SEARCH_END_STATIC
    variables to initialize the LINK_SEARCH_START_STATIC and
    LINK_SEARCH_END_STATIC target properties respectively.

**Pull request closed without merging**
