### PR TITLE
ApplyPatches: Fix finding of patch.exe if installed in user folder

### PR DESCRIPTION
**Pull request by jcfr**
Reported-by: Andras Lasso <lasso@queensu.ca>

### CODE REVIEW

**Comment by jcfr** [comment]
All CI passed (still waiting on macOS).

**Comment by lassoan** [comment]
Thank you, this should solve the problem in many cases.

The CMake error that is logged now comes quite late and it is buried among lots of other messages, so it's difficult to figure out what's wrong. It would be great if patch.exe not found error was reported when configuring the top-level superbuild project (and if found then the location would be passed to subprojects that need it).

**Comment by jcfr** [comment]
> top-level superbuild project 

working on that now

**Comment by jcfr** [comment]
See https://github.com/Slicer/Slicer/pull/781

**Comment by lassoan** [comment]
Perfect, thank you!

**Pull request merged**
