### PR TITLE
DIRECTORY not available in CMake <=2.8.11. PATH should be used instead

### PR DESCRIPTION
**Pull request by robguinness**
In older versions of CMake (<= 2.8.11), DIRECTORY is not available. PATH should be used instead if these older versions of CMake. See: https://cmake.org/cmake/help/v2.8.12/cmake.html#command:get_filename_component

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the fix @robguinness . Will integrate as soon as tests are done.

Out of curiosity, we have been talking about updating the minimum required version of CMake to be a recent 3.x version.

I am curious to know what are you thoughts ?

**Comment by robguinness** [comment]
Hmm....I certainly understand the desire to do so, but I am actually using your build system at the moment to build Python on an old Linux VM (which comes with an old version of CMake). The reason for me doing this is admittedly a bit silly. I'm trying to build a Python binary that will work on old systems, and thus I need to ensure it doesn't rely on any new features of glibc. I haven't been able to figure out any other way to achieve this apart from building on a system with an ancient version of glibc. Probably there is a better way...

**Comment by jcfr** [comment]
> Python binary that will work on old systems [...] I haven't been able to figure out any other way to achieve this apart from building on a system with an ancient version of glibc.

In that case, you could use the `dockbuild/centos7-devtoolset4-gcc5:latest` docker image. See https://github.com/dockbuild/dockbuild#readme

It is based on centos7 (a distribution based on a old enough GLIBC) but it provides a recent g++ version.

**Comment by jcfr** [comment]
As a side note, you may want to update your local installation  of git so that your email is the correct one. The patch we integrated currently specify the following and it prevents your contribution from referencing your profile:

```
From: Rob G <rob@localhost.localdomain>
```

**Pull request merged**
