### PR TITLE
Python 3.6.2 Support

### PR DESCRIPTION
**Pull request by kreuzberger**
Wanted to integrate newest Python 3.6.2

- Added md5sum for Python 3.6.2
- Fixed an install error when installing into different directory with make install DESTDIR=/...
- Python 3.6.2 does not generate a _sysconfigdata.py any more, seems to add MACHDEP as part of the filename. So dependency checking for generation of _sysconfigdata.py does not work and install fails.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the patch :+1:

Would it be possible to update the topic to add testing of Python 3.6.2. See travis.yml and appveyor.yml ?

**Comment by kreuzberger** [comment]
Hi!
Just to clarify for me: you want me to update the travis.yml and appveyor.yml to enable testing for 3.6.2 in the same pull request here?

**Comment by kreuzberger** [comment]
ok, the pull request seems to fail due to the continuous builds. i cannot find the log files to determine what failed, i just can see in the travis log that where was an compiler error. I am working with gcc 5.4 under a debian system.
Error(s) when building project
   15 Compiler errors
   2 Compiler warnings
	Add file: /tmp/travis_dashboard.cmake
	Add file: /tmp/python_common.cmake

But i cannot find any details? Where are the logs stored?
Any help appreciated :-)

**Comment by kreuzberger** [comment]
giving up cause do not know what the problem is. tested with gcc 4.8 on an older linux, getting compiler errors from python itself and do not know how to handle the tests to compile with c99 oder to patch the 3.6.2 code?

**Pull request closed without merging**
